MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  FCOS_ON: True
  RPN_ONLY: False
  BACKBONE:
    CONV_BODY: "R-50-FPN-RETINANET"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
  FPN:
    ONLY_P6: False
    ATT_DENSE: True
    DENSE: True
  FCOS:
    CENTER_WEIGHT: 1.0
  RETINANET:
    USE_C5: False # FCOS uses P5 instead of C5
  ROI_HEADS:
    USE_FPN: True
  ROI_MASK_HEAD:
    POOLER_SCALES: (0.125, 0.0625, 0.03125, 0.015625, 0.0078125)
    FEATURE_EXTRACTOR: "InstanceSaliencyMaskDecoder"
    PREDICTOR: MaskDecoderPredictor
    CONV_LAYERS:  (128, 128, 128, 128)
    POOLER_RESOLUTION: (32, 16, 8, 4, 4)
    POOLER_SAMPLING_RATIO: 2
    RESOLUTION: 32
    SHARE_BOX_FEATURE_EXTRACTOR: False
  MASK_ON: True
  SEG_ON: False
  SEG_ON_ADD_CHANEL: False
DATASETS:
  TRAIN: ("come_train_cocostyle",)
  TEST: ("come_test_e_cocostyle",)
INPUT:
  MIN_SIZE_TRAIN: (320, )
  MAX_SIZE_TRAIN: 480
  MIN_SIZE_TEST: 320
  MAX_SIZE_TEST: 480
SOLVER:
  BASE_LR: 0.005
  WEIGHT_DECAY: 0.0001
  STEPS: (20000, )
  MAX_ITER: 30000
  IMS_PER_BATCH: 8
  WARMUP_METHOD: "constant"
  CHECKPOINT_PERIOD: 10000
DATALOADER:
  SIZE_DIVISIBILITY: 32
TEST:
  IMS_PER_BATCH: 1
