MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/FAIR/20171220/X-101-32x8d"
  FCOS_ON: True
  RPN_ONLY: False
  BACKBONE:
    CONV_BODY: "R-101-FPN-RETINANET"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
    STRIDE_IN_1X1: False
    NUM_GROUPS: 32
    WIDTH_PER_GROUP: 8
  FPN:
    ONLY_P6: False
    ATT_DENSE: True
    DENSE: True
  FCOS:
    CENTER_WEIGHT: 1.0
  RETINANET:
    USE_C5: False # FCOS uses P5 instead of C5
  ROI_HEADS:
    USE_FPN: True
  ROI_MASK_HEAD:
    POOLER_SCALES: (0.125, 0.0625, 0.03125, 0.015625, 0.0078125)
    FEATURE_EXTRACTOR: "InstanceSaliencyMaskDecoder"
    PREDICTOR: MaskDecoderPredictor
    CONV_LAYERS:  (128, 128, 128, 128)
    POOLER_RESOLUTION: (32, 16, 8, 4, 4) #(14,) #
    POOLER_SAMPLING_RATIO: 2
    RESOLUTION: 32
    SHARE_BOX_FEATURE_EXTRACTOR: False
  MASK_ON: True
  SEG_ON: False
  SEG_ON_ADD_CHANEL: False
DATASETS:
  TRAIN: ("isod_train_cocostyle",)
  TEST: ("isod_test_cocostyle",)
INPUT:
  MIN_SIZE_TRAIN: (320,)
  MAX_SIZE_TRAIN: 480
  MIN_SIZE_TEST: 320
  MAX_SIZE_TEST: 480
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  WEIGHT_DECAY: 0.0001
  BASE_LR: 0.0025
  STEPS: (6000, )
  MAX_ITER: 9000
  IMS_PER_BATCH: 4
  WARMUP_METHOD: "constant"
  CHECKPOINT_PERIOD: 1000
TEST:
  IMS_PER_BATCH: 1
